# Generated by Django 5.1 on 2026-07-09 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("superfilter", "0002_savedsuperfilter_columns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedsuperfilter",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Filtre enregistré",
                "verbose_name_plural": "Filtres enregistrés",
            },
        ),
    ]
